Feature/report post
m3ntorship/pickly-backend pull request #81
Opened 2020-11-18 19:46 UTC by abdelrhmanali29

add report post feature

- [ ] update swagger file

- [ ] route

- [ ] complete service

2020-11-18 21:00 UTC, Nilegfx requested changes

2020-11-18 21:00 UTC, Nilegfx commented on m3ntorship-Posts-1.0.0-swagger.json
> +                  "informerId": {
reporterId

2020-11-18 21:00 UTC, Nilegfx commented on m3ntorship-Posts-1.0.0-swagger.json
> +            "description": "Post Not Found"
not found error

2020-11-18 21:00 UTC, Nilegfx commented on m3ntorship-Posts-1.0.0-swagger.json
> +      "put": {
why would you change this!

2020-11-19 11:06 UTC, abdelrhmanali29 commented on m3ntorship-Posts-1.0.0-swagger.json
> +      "put": {
based on saif request

2020-11-19 11:47 UTC, Nilegfx commented on m3ntorship-Posts-1.0.0-swagger.json
> +      "put": {
you both shouldn't do this. a PR has to only contain what it meant to solve and not mixing concerns like this one as it is unclear for a reviewer like me why certain change is made in different areas of the swagger file.

in this case, please separate the swagger file in its own PR for me to review. this PR should be Posts openAPI definitions. 

in the future, I'll close any PR that might be a source of confusion for others or it has too many changes/concerns. do NOT accumulate API specifications as it should be done first thing before jumping into any implementations.

2020-11-20 18:05 UTC, closed without merging